repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args:
            - --line-length=104
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args:
            - --max-line-length=104
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        args:
            - --ignore-missing-imports
            - --disallow-untyped-calls
            - --disallow-untyped-defs
            - --disallow-incomplete-defs
            - --warn-redundant-casts
            - --warn-unreachable
            - --show-error-context
            - --pretty
        language: system
